### PR TITLE
Access component in template directly

### PR DESCRIPTION
**Pull request by jensljungblad**
This PR goes even further than https://github.com/varvet/components/pull/4 and should be seen as an alternative. Instead of having to access the component via a variable, method calls are delegated to the component. Not sure if this is a good strategy or not, I couldn't think of any other sane way of accomplishing this.

I experimented with the `dry-view` library for a bit and got it working by providing the component as the `context` of the view, but that comes with a whole slew of issues, having to mix in all the Rails helpers, etc.

### CODE REVIEW

**Comment by jensljungblad** [comment]
Actually this is pretty bad because it wont work with nested components.. But I just thought of another approach that should solve that!

**Comment by jensljungblad** [comment]
Pushed 8d108c4 which should take care of nested components. Overriding `method_missing` on the Rails view felt a bit crazy also, while here it seems fine. Perhaps it's possible to forego `method_missing` altogether, by using some other delegation technique, or by redefining the methods  on the view and then cache the view classes per component name or something.

**Comment by jensljungblad** [comment]
Pushed 2e8378f which foregoes `method_missing` altogether, in favor of doing some `delegate` when instantiating the view wrapper.

**Comment by Linuus** [comment]
I don't really like to just call "random" methods without an explicit receiver. Feels a bit too magical and confusing to me.

**Comment by Linuus** [comment]
Also, I think this would override rails view helpers if there are name clashes, right?

**Comment by jensljungblad** [comment]
@Linuus Yeah it would take precedence, which I would say is desirable. Helpers in Rails kinda goes against the whole concept of isolated components so it's a bit unfortunate they're there :/

This is how other libraries like cells and mountain view deals with this, and from an isolated component perspective I think the interface makes sense. Optimally you would only have access to specified attributes and helpers within your template but since this is Rails we should probably still allow helpers like `link_to` etc :) And since they're mixins I thought it probably makes sense to keep the Rails view as the context of the rendered partial.

**Comment by Linuus** [comment]
@jensljungblad I misread the code (I've never really looked at this library :) ). I thought you were delegating all methods to the model/object. But you are just delegating to the component, right? Can we only delegate the methods that were explicitly added with the `attribute` method instead of all public methods?

**Comment by jensljungblad** [comment]
@Linuus Correct. The idea with the library is to also provide an alternative to helpers, at least for components. Check out https://github.com/varvet/components#helper-methods. If we would scrap this feature, then yes, we could just delegate the attributes to the component, or rather, just pass the attributes as locals instead of delegating. If we want to support these "helper methods" on the other hand, we need to delegate those somehow.

Rails helpers in general are a bit problematic for styleguides and isolated components, which is why this is a bit tricky. Helpers are sort of global. Let's say you define a `current_user` helper that is available globally across all views, and that instead of passing a user explicitly to your component, you use this helper from your component template. That means your component is tied to a particular (controller) context. If the styleguide is displayed in a different context (let's say we bundle a styleguide with this gem for instance) then the `current_user` helper will be missing. The built in Rails helpers, on the other hand, should perhaps be considered global, and be considered to also exist in the styleguide context.

**Comment by Linuus** [comment]
Right, I didn't think of the helper methods...

Also, Rails helpers suck for all sorts of reason :D

**Comment by jensljungblad** [comment]
Well, turns out using a `SimpleDelegate` was not a good solution, because Rails is using the object id in all sorts of ways when compiling templates..! Switched back to a `method_missing` for now. 

This is similar to how mountain view does it, but they add delegations to the class of the view, which adds the delegations to all views, but in most render passes the object they delegate to does not exist, which results in weird error messages in my opinion.. It might be more performant than `method_missing` though. Is there another way to add methods to an object instance without adding them to its class?

**Comment by jensljungblad** [comment]
Well, I read up on it a little and delegation was indeed possible, using Ruby's `singleton_class`, which is a special anonymous class wrapping instances. And it's possible to run `delgate` on that, which only adds delegation for that particular instance.

**Pull request merged**
